### ISSUE TITLE
Exercicio 01

### ISSUE THREAD

**Issue by rvenson** [ardnaile/back-end#1]
https://github.com/ardnaile/back-end/blob/d1737d16186fa30f52ef073e9743d6df8a753a43/exercicios/exercicio01_resolvido/src/main/java/org/example/Main.java#L49C1-L49C64

A lista de posição vem com caracteres que precisam ser sanitizados. É possível limpar usando o `string.replace`

https://www.baeldung.com/string/replace

**Comment by ardnaile** [comment]
Ok, muito obrigada professor. Resolvido!
